second commit
Roman2106/secondProgect pull request #1
Opened 2017-09-11 10:04 UTC by Roman2106

2017-09-18 12:08 UTC, stasshiray requested changes

2017-09-18 12:08 UTC, stasshiray commented on server/index.js
> +const fs = require("fs");
Не используется

2017-09-18 12:08 UTC, stasshiray commented on server/index.js
> +app.use(express.static(path.join(__dirname,'static')));
`app.use(express.static)` не нужен, если нужна статика, лучше хранить в проекте `client` в папке `public`, так удобнее - все вещи необходимы для работы фронтенда в одном месте

2017-09-18 12:08 UTC, stasshiray commented on server/index.js
> +app.set("view engine", "ejs");
Оба `app.set` не нужны, т.к. серверные `ejs` шаблоны не используются

2017-09-18 12:08 UTC, stasshiray commented on client/src/App.js
> +                {id: "Trips", title: "Trips", key: this.generateKey()},
Здесь лучше использовать не генерируемы ключи, а что-нибудь типа `key: 'trips'` и `key: 'customers'`

2017-09-18 12:08 UTC, stasshiray commented on client/src/Trips.js
> +			routName: "",
Форму добавления лучше выделить в отдельный компонент и создавать trip по нажатию на кнопку "Добавить маршрут". Примерно так:
```jsx
class TripForm extends React.Component {
    constructor(props) {
         super(props);
         this.state = { tripName: props.tripName || ''};
    }
   
    onSubmit(evt) {
         evt.preventDefault();
         const {tripName} = this.state;
         this.props.onSave({tripName});
    } 

    render() {
          <form onSubmit={evt => this.onSubmit(evt)} >
               <input type="text" onChange={evt => this.setState({tripName: evt.target.value})} value={this.state.tripName/>
               <button type="submit">Сохранить</button>
          </form>
    }
```
Тогда в `Trips` можно будет использовать его и для добавления и для изменения (как в 4м занятии)

2017-09-18 12:08 UTC, stasshiray commented on client/src/Trips.js
> +						<tr key = {this.generateKey()}>
Использовать `generateKey` не очень хорошая идея т.к. при любом перерендеринге ключи будут все равно увеличиваться, т.е. каждый элемент получит новый ключ и во всех `tr` будет перерендеринг аттрибутов. Чуть лучшим вариантом было бы использование `index` но у него потенциально похожие проблемы, если поменяться порядок элементов в allTrips, то у всех `tr` будут переписаны аттрибуты. Лучший вариант для ключа использовать `item.id`, тогда при перендериге и при смене порядка в элементов в `allTrips` теги `tr` будут просто переставлены местами, это несколько более быстрая операция

2017-09-18 12:08 UTC, stasshiray commented on client/src/Trips.js
> +				<button className = "update" onClick = {this.apdateTrip.bind(this)}>Применить изменения</button>
Надо как минимум использовать `disabled` типа `<button onClick={...} disabled={this.state.idForUpdate === null}></button>
Сейчас можно нажать на кнопку "Применить изменения" до нажатия на "Изменить" и получить ошибку. Лучше вынести всю форму в отдельный компонент. Или как минимум дисеблить кнопку добавления если `idForUpdate !== null` и кнопку применения изменений, если `idForUpdate === null`

2017-09-18 12:08 UTC, stasshiray commented on client/src/Trips.js
> +apdateTrip(){
`updateTrip`

2017-09-18 12:08 UTC, stasshiray commented on client/src/Trips.js
> +	update("trips", id, obj);
Надо дождаться выполнения `update` (это `Promise`). `update` выполняется асинхронно, поэтому нет гарантии, что изменения сохранятся до того, как вы прочитаете с сервера новые данные через `getAll`, т.е. вы можете получить не обновленные данные. А еще `update` может вернуть ошибку. Поэтому надо дожидаться завершения `update`.
```js
update('trips', id, obj).then(() => getAll('trips'))
    .then(arr => this.setState({allTrips: arr})
    .catch(error => // обработка ошибки, показ сообщения);
```
Пока что в задании нет условий, которые делают `getAll` обязательным, поэтому можно просто обновить данные сразу в массиве
```js
update('trips', id, obj).then(updatedObject => this.setState(state => {
    const index = state.allTrips.findIndex(trip => trip.id === updatedObject.id);

    return {
         ...state,
         allTrips: [
             ...state.allTrips.slice(0, index),
             updatedObject,
             ...state.allTrips.slice(index + 1)
         ]     
    };
}));
```

2017-09-18 12:08 UTC, stasshiray commented on client/src/Trips.js
> +	remove(url, id);
Тоже самое, что и с `update`, `remove` может не пройти, нужно либо дождаться успеха, либо убрать элемент из массива, а в случае провала в `catch` вернуть его назад в массив

2017-09-28 13:46 UTC, stasshiray requested changes

2017-09-28 13:46 UTC, stasshiray commented on client/src/App.js
> +import WrapperTrips from "./WrapperTrips";
WrappedTrips плохое название, сразу вопрос возникает, во что обернуты компоненты Trips. Лучше просто Trips или TripsScreen

2017-09-28 13:46 UTC, stasshiray commented on client/src/App.js
> +        activeMenu: "Trips"
Заведите константы
```
const MenuItems = {
    Trips: 'Trips',
    Locations: 'Locations',
    Customers: 'Customers'
};
```
Тогда можно будет писать `this.state.activeMenu === MenuItems.Trips` и если в будущем строка Customers превратиться в Clients, то надо будет поменять только в объекте MenuItems, а не смотреть для каждой строки со словом Customers надо ее менять или нет

2017-09-28 13:46 UTC, stasshiray commented on client/src/Customers.js
> +				<div>Loading data...</div>
Я бы сделал универсальный компонент `<Loader />`, который бы использовал во всех таких местах. Пусть он для начала возвращает  `<div>Loading data...</div>`, но потом его можно будет переписать с анимацией какой-нибудь, типа крутящегося чего-нибудь и, главное, в одном месте

2017-09-28 13:46 UTC, stasshiray commented on client/src/WrapperCustomers.js
> +class WrapperCustomers extends React.Component{
Просто Customers. Или CustomersScreen. А то, что у вас называется Customers - CustomersList

2017-09-28 13:46 UTC, stasshiray commented on client/src/WrapperCustomers.js
> +			btnVal: "",
Не используйте таких сокращений, затрудняет чтение. `buttonValue` и `objectForEdit`. Хотя лучше назвать было бы customerForEdit или как-то так. А `btnValue`, кажется, вообще не нужен, т.к. он равен add тогда когда objForEdit === "", т.е. что нужно рендерить можно определить только по одному objForEdit

2017-09-28 13:46 UTC, stasshiray commented on client/src/Trips.js
> +			        				this.props.getById(item.id);
Prop лучше назвать onEditClick. Такое название лучше описывает, что происходит. Пользователь нажал на кнопку edit и что-то случилось.

2017-09-28 13:46 UTC, stasshiray commented on client/src/Trips.js
> +			        			this.props.delSingle(item.id, index).then(() =>{
Пропертю лучше назвать `deleteSingle` или `deleteCustomer` или просто `delete` (не без сокращений)

2017-09-28 13:46 UTC, stasshiray commented on client/src/WrapperCustomers.js
> +			viewType: "customers",
Заведите константы для viewType

2017-09-28 13:46 UTC, stasshiray commented on client/src/WrapperCustomers.js
> +			objForEdit: ""
Почему значение по умолчанию - пустая строка? Там должен быть объект, поэтому null

2017-09-28 13:46 UTC, stasshiray commented on client/src/form_for_customers.js
> +class TripsForm extends React.Component{
Почему TripsForm, если это форма добавления Customer'а? Сейчас можно добавить несколько раз один и тот же три и он несколько раз сохраниться в базе. Нужно добавить проверку и на клиенте и на сервере, чтобы этого не происходило. Например, сравнивать по id, добавлен ли уже такой trip

2017-09-28 13:46 UTC, stasshiray commented on client/src/form_for_customers.js
> +import React from "react";
Называйте файлы однотипно. Это `CustomersForm.js` по аналогии с большинством других файлов

2017-10-11 10:03 UTC, stasshiray commented on client/src/tests/FormForTrips.test.js
> +import React from "react";
С тестом несколько проблем. 
1) Компонент ходит на сервер. Тест падает, так как из теста даже на запущеный сервер сходить не выходит. Чинится путем подмены функции, которая делает запрос на сервер
```
import * as Api from '../api/api';
Api.getAll = () => Promise.resolve([]);
```
2) Проблема опять же от похода на сервер. Компонент не успевает перендерится до конца теста и нет промиса, который может подождать. Поэтому можно проверить, есть ли кнопка с селектором, если нет, подождать пока не появиться (проверять, например, 5 раз с интервалом в секунду, появилась ли, если нет - тест не пройден). 
В итоге получается что-то типа:
```
import React from "react";
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import {mount} from "enzyme";
import TripsForm from "../formForTrips";
import * as Api from "../api/api";

const originalGetAll = Api.getAll;
let locationsPromise;

beforeEach(() => {
  locationsPromise = Promise.resolve([]);
  Api.getAll = () => locationsPromise;
});

afterEach(() => {
  Api.getAll = originalGetAll;
});

Enzyme.configure({ adapter: new Adapter() });

const waitForElement = (wrapper, selector, interval = 1000, times = 5) => new Promise((resolve, reject) => {
  const element = wrapper.find(selector);
  if (element.length > 0) {
    resolve(element);
  } else {
    const intervalHandle = setInterval(() => {
      wrapper.update();      
      const element = wrapper.find(selector);
      if (element.length > 0) {
        clearInterval(intervalHandle);
        resolve(element);
        return;
      }
      times--;
      if (times === 0) {
        throw new Error('Element was not found');
      }
    }, interval);
  } 
});

const waitForTimeout = timeout => new Promise(resolve => setTimeout(resolve, timeout));

it("Should call onAdd, by pressing the button 'Add Trip'", () => {
  const onAdd = jest.fn();
  const onError = jest.fn();
  const wrapper = mount(<TripsForm onAdd = {onAdd} btnVal="add" onAdd={onAdd} onError={onError}/>);
  
  return waitForElement(wrapper, '.addEditTrips').then(button => {
    button.simulate("click");
    expect(onAdd.mock.calls.length).toBe(1);
  });
});
```
Это тест все равно упадет не пройдет, т.к. будет вызван не `onAdd`, а `onError` из-за того, что не заполнены поля формы. Для тестирования onAdd нужно заполнеить поля формы, например для tripName:
```
 return waitForElement(wrapper, '.addEditTrips').then(button => {
    const tripNameInput = wrapper.find('#tripName');
    tripNameInput.simulate('change', {target: {value: 'some name'}});
    button.simulate("click");
    expect(onAdd.mock.calls.length).toBe(1);
  });
```
Для меня выглядит так, что нужно переструктурировать приложиние. Доставать данные по locations должна не форма, а кто-то из родителей.  Тогда не будет проблем из-за промиса. Есть лишние коллбеки. Например, onSuccess вызвать в этом месте еще рано, лучше после похода на сервер и реального сохранения данных. Нет смысла разделять onAdd и onUpdate, они абсолютно одинаковые.Можно сделать один onSave и потом решать это add или update в родителе или колббеке, например, по наличию id, как это сделано в примерах с занятий для добаления user'а

2017-10-11 10:34 UTC, Roman2106 commented on client/src/tests/FormForTrips.test.js
> +import React from "react";
Спасибо Стас) 
У меня не только locations форма достает. У меня еще CustomerForm достает trips))
Кароче проблема на проблеме) Много чего переделывать переписывать)

2017-10-20 06:58 UTC, merged