Redux
Roman2106/secondProgect pull request #2
Opened 2017-10-30 16:23 UTC by Roman2106

2017-11-04 10:18 UTC, stasshiray requested changes

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Customers/CustomersService.js
> +          dispatch(addCustomer(customer)), dispatch(setMessage(`${customer.firstName} - ${customer.lastName} was successfully add.`, "success"))
Не понял, зачем возвращать массив в `then`. Чтобы не было 2-х ре-рендерингов, надо в `dispatch` массив передавть. `dispatch([addCustomer(customer), setMessage(...)])`

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Customers/CustomersService.js
> +        setTimeout(() => [
Зачем искуственно задерживать получение пользователей?

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Customers/CustomersService.js
> +export const CustomersService = {
Лучше назвать `CustomersActionCreators`. Для функций, которые возвращают redux action, который дальше передается в `dispatch`, устоявшееся название - action creator. Те функции, которые импортируются из `CustomersReducer` тоже action creator'ы, поэтому их лучше держать в одном файле с теми, которые в `CustomersService`

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Customers/CustomersTable.js
> +    this.state = {}
Т.к. `setState` нету, `state` не нужен. Можно вообще весь конструктор удалить.

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Locations/LocationsTable.js
> +    } else {
`else` ветку можно не писать, просто делать `return <Loader />` после `if`, т.е. если внутри `if` есть `return` можно делать так
```js
if (someCondition) {
    return someValue;
}

return otherValue;
```

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Trips/TripsReducer.js
> +  listTrips: [],
Инициализированно массивом, хотя в reducer'е устанавливается в объект, в котором ключ - id, значение - trip. Лучше проинициализировать `null`.

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Trips/TripsReducer.js
> +      let customerWithId = _.keyBy(action.payload.trips, trip => trip.id);
Почему переменная называется `customerWithId`, когда там не customer, а trip? copy-paste?

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Trips/TripsReducer.js
> +      newlistTrips = customerWithId;
Ненужное присваивание?

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Trips/TripsReducer.js
> +      let newlistTrips = clone(state.listTrips);
`clone` здесь не нужен. это deep copy, т.е. когда копируются все вложенные объекты и их вложенные объекты и т.д. Достаточно shallow copy, т.е. компируется только верхний уровень, вглубь не идет. Разница описана [тут](http://blog.soulserv.net/understanding-object-cloning-in-javascript-part-ii/)
Если все-же зачем-то понадобился deep clone, он уже есть в `lodash` - `_.cloneDeep`.
К тому же, похоже, что в `action.payload.trips` прилетают все trips сразу, поэтому предыдущее значение `listTrips` не важно.
Лучше было бы сделать как-то так:
```js
case ActionType.LOADED_TRIPS:
    return {...state, showLoading: false, listTrips: _.keyBy(action.payload.trips, trip => trip.id)};
```
Если же в `action.payload.trips` только, например, страница, тогда можно сделать так:
```js
case ActionType.LOADED_TRIPS:
    const normalizedTrips = _.keyBy(action.payload.trips, trip => trip.id);
    return {...state, showLoading: false, listTrips: {...state.listTrips, ...normalizedTrips}};
```

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Trips/TripsReducer.js
> +      let newTripsArr = Object.keys(newTrips).reduce((arr, key) => ([...arr, { ...newTrips[key] }]), []);
Похоже, что после загрузки все trips - это объект, а потом они трансформируются в массив. и храняться в массиве. Надо выбрать одно из 2-х - либо хранить в массиве, либо в объекте. Если в объекте, тогда не нужно каждый раз трансформировать в массив для изменения. Тогда правильно будет как-то так:
```js
case ActionType.LOADED_TRIPS:
    return {...state, isLoading: false, listTrips: _.keyBy(action.payload.trips, trip => trip.id)};
case ActionType.ADD_TRIP:
case ActionType.EDIT_TRIP:
    return {...state, listTrips: {...state.listTrips, [action.payload.trip.id]: action.payload.trip}}
case ActionType.DELETE_TRIP:
    return {...state, listTrips: _.omit(state.listTrips, action.payload.id)};
```
Похоже, в целом, стоит обратить внимание на [этот список доков](http://redux.js.org/docs/recipes/reducers/PrerequisiteConcepts.html#immutable-data-management) и [док про изменение состояние в redux](http://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html)

2017-11-04 10:18 UTC, stasshiray commented on client/src/components/Trips/TripsScreen.js
> +      let tripsArr = Object.keys(trips).reduce((arr, key) => ([...arr, {...trips[key]}]), []);
Я бы делал `connect` на каждый скрин, чтобы пробрасывать меньше пропов по дереву компонентов вниз и логику трансформации объекта в массив перенес в `mapStateToProps`.

2017-11-04 17:22 UTC, Roman2106 commented on client/src/components/Customers/CustomersService.js
> +        setTimeout(() => [
Я извиняюсь, хотел прикрутить на Loader спинер недоприкрутил и забыл убрать setTimeout

2017-11-04 17:29 UTC, Roman2106 commented on client/src/components/Trips/TripsReducer.js
> +      let customerWithId = _.keyBy(action.payload.trips, trip => trip.id);
Ага))

2017-11-04 17:30 UTC, Roman2106 commented on client/src/components/Trips/TripsReducer.js
> +      newlistTrips = customerWithId;
Согласен что то я тут перемудрил вообще...

2017-11-04 17:33 UTC, Roman2106 commented on client/src/components/Trips/TripsScreen.js
> +      let tripsArr = Object.keys(trips).reduce((arr, key) => ([...arr, {...trips[key]}]), []);
Спасибо буду разбираться.

2017-11-09 10:07 UTC, stasshiray requested changes

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersActionCreators.js
> +export const CustomersService = {
`CustomersActionCreators`

2017-11-09 10:07 UTC, stasshiray commented on client/package.json
> +    "redux-batch": "0.0.0",
Если вы используете `redux-batched-actions`, то `redux-batch`, кажется, не нужен. Тоже самое касается и `@manaflair/redux-batch`

2017-11-09 10:07 UTC, stasshiray commented on client/package.json
> +    "clone": "^2.1.1",
Кажется не используется, можно убрать из зависимостей.

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersScreen.js
> +      super(props);
`this.setState` не делается, поэтому `this.state` не используется, поэтому конструктор можно удалить

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersScreen.js
> +      let tripsWithKeys = _.keyBy(trips, trip => trip.id);
Судя по `TripsReducer` `listTrips` уже объект, зачем делать `keyBy`? В целом кажется, что для всех сущностей в стейте хранится нормализованный объект, а все компоненты работают с массивами. Почему бы не вынести логику приобразования в объекта в массив в `mapStateToProps` и убрать ее из всех компонентов? А если все-же какому-то компоненту нужен объект, а не массив - можно в `mapStateToProps` возвращать в одном свойстве объект, в другом массив. Типа такого:
```js
function mapStateToProps(state) {
    return {
        customers: {
            normalizedCustomers: state.customers.listCustomers,
            customersList: Object.values(state.customers).reduce((accum,value) => ([...accum, ,value]), [])
        }
    };
}
```

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersReducer.js
> +};
Оставляйте пусту строку вконце файла

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +            this.props.history.push(`/customers?page=${String(currentPage)}`);
Правильнее было бы застилизовать `NavLink` под кнопку и передавать в него url. Тогда не нужно будет передать `history` через `props`.

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +    let currentPage = queryParams.page >= 1 ? parseInt(queryParams.page, 10) : 1;
Вместо использования `window.location.search` правильнее сделать следующее:
1) Добавить в props свойство `returnUrl` в котором бы уже был url на который нужно перейти по нажатию на Cancel или Save
2) Рассчитывать этот url в `CustomersScreen`
3) Для формирования url использовать не `window.location.search`, а  `history.location.search`. Это может пригодиться в тестах (где window, если я правильно помню, может вообще не быть, когда они запускаются из консоли)

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +              {Object.keys(trips).map(item =>
Не используйте `Object.keys`, используйте `Object.values`, у вас и так в значении есть `id`, ключ вам нужен исключительно для быстрого поиска нужного объекта по id. 
Не надо пихать в аттрибут `value` весь объект, достаточно только `id`, это быстрее будет работать и меньше лишних данных будет в DOM.
```js
{Object.values(trips).map(trip => 
    <option key={trip.id} value={trip.id}>
         {`${trip.tripName}. Date departure: ${trip.dateDeparture}.`}
     </option>
}
```

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +      currentTripID.push(selTripId);
Это мутация массива, а нам нужно копировать и добавлять id, как и в redux. Правильное обновление будет через functional setState `this.setState(({customersTripsId}) => ({customersTripsId: [...customersTripsId, selTripId], disabled: false})`

2017-11-09 10:07 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +          this.props.showMessage("Such a trip already exists in the customer", "danger");
А такая ситуация вообще возможна? Кажется, что если trip уже выбран, то юзер должен видеть что он выбран и не иметь возможности выбрать его. Перед тем как показывать ренедерить `option`  можно убирать trips, которые уже выбраны. Это упростит жизнь пользователю и код компонента

2017-11-09 16:47 UTC, Roman2106 commented on client/package.json
> +    "clone": "^2.1.1",
Убрал

2017-11-09 16:48 UTC, Roman2106 commented on client/package.json
> +    "redux-batch": "0.0.0",
Да не нужны убрал

2017-11-09 16:48 UTC, Roman2106 commented on client/src/components/Customers/CustomersActionCreators.js
> +export const CustomersService = {
Изменил

2017-11-09 17:02 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +      currentTripID.push(selTripId);
Исправил

2017-11-09 17:45 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +    let currentPage = queryParams.page >= 1 ? parseInt(queryParams.page, 10) : 1;
да так лучше исправил

2017-11-09 18:36 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +              {Object.keys(trips).map(item =>
исправил

2017-11-09 18:49 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +            this.props.history.push(`/customers?page=${String(currentPage)}`);
исправил

2017-11-09 18:50 UTC, Roman2106 commented on client/src/components/Customers/CustomersReducer.js
> +};
ок

2017-11-09 18:51 UTC, Roman2106 commented on client/src/components/Customers/CustomersScreen.js
> +      super(props);
исправил

2017-11-09 19:43 UTC, Roman2106 commented on client/src/components/Customers/CustomersScreen.js
> +      let tripsWithKeys = _.keyBy(trips, trip => trip.id);
Исправил с помощью Object.values() я про него совсем забыл

2017-11-10 20:50 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +          this.props.showMessage("Such a trip already exists in the customer", "danger");
Согласен,не очень логично переделал

2017-11-11 09:38 UTC, stasshiray requested changes

2017-11-11 09:38 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +          <Link className="cancel" to={`/customers?page=${String(this.props.currentPage)}`}
Ну вот не так же сделали, как я написал. Передавать надо не `currentPage`, а прям url, т.е. что-то типа:
```js
<CustomersForm returnUrl={`customers?page=${this.props.currentPage}`}
```
А в коде формы
```js
...
<Link to={this.props.returnUrl} />
...
```
Нужно это для того, чтобы форму можно было использовать в других местах, не только из таблицы заказчиков. Например, в вашем приложении появилось требование уметь добавлять заказчиков из формы добавления заказов, чтобы быстро оформить покупателя. А форма добавления заказчика умеет возвращаться только на определенную страницу таблицы заказчиков, а надо вернуться в другое место.

Делать явно `String(this.props.currentPage)` не нужно, в templated string значение внутри `${}` и так будет преобразовано в строку

2017-11-11 09:38 UTC, stasshiray commented on client/src/components/Customers/CustomersScreen.js
> +              customer={Object.values(this.props.customers.listCustomers).find(customer => customer.id === match.params.id)}
Зачем преобразовывать к массиву и делать `find` если у вас в объекте `listCustomers` ключ и так id. Правильно `customer={this.props.customers.listCustomers[match.params.id]`. Возможны проблемы только, если ключи - числа (а не строки, содержащие те же числа), тогда надо еще распарсить в число `customer={this.props.customers.listCustomers[parseInt(match.params.id)]}`

2017-11-11 09:38 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +          for (let i = 0; i < Object.values(trips).length; i++) {
Дважды делать `Object.values` на одном объекте - не комильфо, сделайте 1 раз и запомните в переменную. А вообще тут не надо делать двумя циклами, у вас `trips`, на сколько я вижу, это объект с ключами в виде id. Тогда для каждого из id в `customersTripsId` надо взять из `trips` объект через `trips[id]`. Т.е.
```js
customersTripsId.map(id => {
    const trip = trips[id]; // или, возможно id.toString() или parseInt(id) в зависимости от того, строка или число ключ в trips
    return <tr key={id}><td>....</td>...</tr>
});
```
Ключем нода лучше использовать id, а не индекс, если id есть.

2017-11-11 09:38 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +    let arr = _.without(Object.keys(trips), ...this.state.customersTripsID);
Если переменная нигде дальше внутри функции не переприсваивается, используйте `const`

2017-11-11 09:38 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +import 'react-select/dist/react-select.css';
Чтобы не писать этот импорт в каждом компоненте, который  использует react-select (а он нужен только 1 раз на приложение, чтобы вебпак включил css'ку при сборке), можно завести отдельный файл, например `bootstrap.js` который будет импортироваться из `index.js` и в котором таки css-ки и прочие зависимости, которые достаточно включить 1 раз будут промисаны

2017-11-11 09:38 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +      selId: ""
Не используется

2017-11-11 17:49 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +import 'react-select/dist/react-select.css';
Исправил ток у меня bootstrap не будет ,назвал файл css.js

2017-11-11 17:51 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +      selId: ""
исправил

2017-11-11 18:10 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +          for (let i = 0; i < Object.values(trips).length; i++) {
Object.values запомнил в let,  key  поставил  id, насчет двух циклов я пожалуй оставлю, просто, во втором цикле у меня идет проверка нет ли случайно среди customersTripsID и id  прилетевших  trips одинаковых, если есть то идет continue и такой trip не отрендерится в таблице trip-ов принадлежащих этому customer -у

2017-11-11 18:11 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +    let arr = _.without(Object.keys(trips), ...this.state.customersTripsID);
исправил

2017-11-11 18:21 UTC, Roman2106 commented on client/src/components/Customers/CustomersForm.js
> +          <Link className="cancel" to={`/customers?page=${String(this.props.currentPage)}`}
Извиняюсь, сразу до конца не догнал зачем так делать. сейчас все исправил.

2017-11-11 18:24 UTC, Roman2106 commented on client/src/components/Customers/CustomersScreen.js
> +              customer={Object.values(this.props.customers.listCustomers).find(customer => customer.id === match.params.id)}
Затупил. Исправил) спасибо

2017-11-13 05:33 UTC, stasshiray commented on client/src/components/Customers/CustomersForm.js
> +          for (let i = 0; i < Object.values(trips).length; i++) {
Что-то я совсем запутался. У вас же тут рендерятся выбранные кастомером трипы. Т.е. вы как раз одинаковые `id` и ищете, для каждого id из `customerTripsId` берете объект из `trips` с тем же `id` и по этому объекту рендерите строку. Поэтому тот вариант, что я написал, на гляднее и производительнее.

2017-11-13 05:37 UTC, stasshiray commented on client/src/components/Trips/TripsForm.js
> +            let arrLocations = Object.values(locations);
Лучше сделать до `tripsLocationsID.map`, например, в самом верху функции. Сейчас получается, что `Object.values` выполняется столько раз, сколько элементов в tripsLocationsID, хотя результат всегда один и тот же. Хотя опять же, тот вариант, что я описывал, был бы правильнее.

И не забывайте про `const`, где переменные не переприсваиваются. У вас почти во всем коде можно смело менять `let` на `const`

2017-11-13 08:21 UTC, Roman2106 commented on client/src/components/Trips/TripsForm.js
> +            let arrLocations = Object.values(locations);
Точно, ну я затупил, получилось что по сути и не исправил.  Про const  учту. Спасибо.

2017-11-15 10:29 UTC, merged